import Head from "next/head";
import Image from "next/image";
import Hero from "../components/home/hero";
import Layout from "../components/layout";
import { useSession } from "next-auth/react";
import { PrismaClient } from "@prisma/client";
import * as teamActions from "../store/modules/team";
import { useSelector, useDispatch } from "react-redux";
import { useEffect } from "react";
import Main from "../pages/main";
export default function Home() {
  const { data: session, status } = useSession();
  const dispatch = useDispatch();
  const teamList = useSelector((state) => state?.team);

  useEffect(() => {
    if (session) {
      fetch("/api/auth/sessionteamapi", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(session.user.email),
      })
        .then((res) => {
          return res.text();
        })
        .then((data) => {
          // console.log(JSON.parse(data));
          // console.log(data);
          let jsondata = JSON.parse(data);
          dispatch(teamActions.maingetteam(jsondata));
        })
        .catch((err) => {
          console.log(err);
        });
    }
  }, []);

  console.log("teamList>>>>", teamList);
  return (
    <div className="lottie anim">
      <Layout>
        <Head>
          <title>projects</title>
          <meta name="description" content="Generated by create next app" />
          <link
            href="https://fonts.googleapis.com/css2?family=Gaegu:wght@300&display=swap"
            rel="stylesheet"
          />
        </Head>
        {teamList.teamList.logo && session ? (
          <Main />
        ) : (
          <section className="flex min-h-screen flex-col items-center justify-center text-gray-600 body-font">
            <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
              <Hero />
            </div>
          </section>
        )}
      </Layout>
    </div>
  );
}
